import httpx
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles
from app.api import routes_documents, routes_chat, routes_projects
from app.core.memory import init_db
from app.core.structured_facts import init_facts_db
from app.core.figures import init_figures_db, FIGURE_DIR
from app.config import settings
from pathlib import Path

Path(settings.chroma_path).mkdir(parents=True, exist_ok=True)
Path(settings.upload_dir).mkdir(parents=True, exist_ok=True)
Path(settings.memory_db_path).parent.mkdir(parents=True, exist_ok=True)
FIGURE_DIR.mkdir(parents=True, exist_ok=True)

app = FastAPI(title="DocRAG - Local Multi-Tenant Document Intelligence")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.exception_handler(httpx.HTTPError)
async def model_backend_unavailable(request: Request, exc: httpx.HTTPError):
    """
    Every LLM/embedding call goes out over httpx to Ollama. If Ollama is down,
    still loading a model, or just slow enough to blow the client timeout, that
    surfaced as an unhandled exception - a bare 500 with a non-JSON body, which
    the UI can only render as a broken response. Return something explicit
    instead, so the failure reads as "the model backend is unavailable" rather
    than "this app is broken".
    """
    detail = (
        f"Model backend ({settings.ollama_host}) did not respond: {type(exc).__name__}. "
        "Check that Ollama is running (`ollama serve`) and that the models "
        f"'{settings.llm_model}' and '{settings.embedding_model}' are pulled."
    )
    return JSONResponse(status_code=503, content={"detail": detail})


@app.on_event("startup")
def on_startup():
    init_db()
    init_facts_db()
    init_figures_db()


app.mount("/figures", StaticFiles(directory=str(FIGURE_DIR)), name="figures")

app.include_router(routes_documents.router)
app.include_router(routes_chat.router)
app.include_router(routes_projects.router)


@app.get("/health")
async def health():
    return {"status": "ok"}


# Frontends are mounted last, at sub-paths, so they never shadow the API routes
# above. Two of them:
#
#   /ui      - the Next.js console (frontend-next), served from its static
#              export. Built with `cd frontend-next && npm run build`; the
#              export is committed-free and regenerated by that command, so if
#              frontend-next/out is missing we fall back rather than 404 the UI.
#   /ui-basic - the original single-file console. Kept deliberately: it needs no
#              build step, so it still works if node tooling is unavailable or
#              the export hasn't been generated on this machine.
_root = Path(__file__).parent.parent
_console_dir = _root / "frontend-next" / "out"
_basic_dir = _root / "frontend"

if _basic_dir.exists():
    app.mount("/ui-basic", StaticFiles(directory=str(_basic_dir), html=True), name="ui_basic")

if _console_dir.exists():
    app.mount("/ui", StaticFiles(directory=str(_console_dir), html=True), name="ui")
elif _basic_dir.exists():
    # console not built on this machine - keep /ui working with the basic one
    app.mount("/ui", StaticFiles(directory=str(_basic_dir), html=True), name="ui")
